import React, { useState, useEffect } from 'react';

import { Cookie, CookieManagerModule } from '../modules/cookieManager';

const CookieManager: React.FC = () => {
  const [cookies, setCookies] = useState<Cookie[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadCookies();
  }, []);

  const loadCookies = async () => {
    try {
      const siteCookies = await CookieManagerModule.getCookiesForCurrentTab();
      setCookies(siteCookies);
    } catch (error) {
      console.error('Error loading cookies:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteCookie = async (cookie: Cookie) => {
    try {
      await CookieManagerModule.deleteCookie(cookie);
      await loadCookies();
    } catch (error) {
      console.error('Error deleting cookie:', error);
    }
  };

  const exportCookiesJSON = () => {
    CookieManagerModule.exportCookies(cookies);
  };

  const exportToClipboard = async (format: 'json' | 'netscape') => {
    try {
      let content: string;
      
      if (format === 'json') {
        content = JSON.stringify(cookies, null, 2);
      } else {
        // Netscape format
        let header = "# Netscape HTTP Cookie File\n";
        header += "# Generated by 4ndr0tools\n";
        header += "# This file contains the HTTP cookies for a single site\n\n";
        
        const netscapeData = cookies.map(cookie => {
          const domain = cookie.domain;
          const subdomainFlag = String(!cookie.hostOnly).toUpperCase();
          const path = cookie.path || '/';
          const secureFlag = String(cookie.secure).toUpperCase();
          const expiration = cookie.expirationDate ? Math.floor(cookie.expirationDate) : '0';
          
          return `${domain}\t${subdomainFlag}\t${path}\t${secureFlag}\t${expiration}\t${cookie.name}\t${cookie.value}`;
        }).join('\n');
        
        content = header + netscapeData;
      }
      
      await navigator.clipboard.writeText(content);
      
      // Show temporary feedback
      const button = document.activeElement as HTMLButtonElement;
      const originalText = button.textContent;
      button.textContent = '✅ Copied!';
      button.style.backgroundColor = 'var(--hud-btn-bg-color-active, #15FFFF)';
      button.style.color = 'var(--hud-btn-text-color-active, #062427)';
      
      setTimeout(() => {
        button.textContent = originalText;
        button.style.backgroundColor = '';
        button.style.color = '';
      }, 1500);
      
    } catch (error) {
      console.error('Error copying to clipboard:', error);
    }
  };

  const handleImportCookies = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = async (e) => {
        try {
          const content = e.target?.result as string;
          const importedCookies = JSON.parse(content);
          await CookieManagerModule.importCookies(importedCookies);
          await loadCookies(); // Reload cookies after import
          alert('Cookies imported successfully!');
        } catch (error) {
          console.error('Error importing cookies:', error);
          alert('Failed to import cookies. Please ensure the file is a valid JSON.');
        }
      };
      reader.readAsText(file);
    }
  };

  const exportSiteCookies = async () => {
    try {
      const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
      if (!tab.url) {
        alert('No active tab found.');
        return;
      }

      const url = new URL(tab.url);
      const cookies = await CookieManagerModule.getCookiesForCurrentTab(); // Use existing module function

      if (cookies.length === 0) {
        alert('No cookies found for this site');
        return;
      }

      const dataStr = JSON.stringify(cookies, null, 2);
      const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
      
      const exportFileName = `cookies_${url.hostname}_${new Date().toISOString().split('T')[0]}.json`;
      
      const linkElement = document.createElement('a');
      linkElement.setAttribute('href', dataUri);
      linkElement.setAttribute('download', exportFileName);
      linkElement.click();

      alert(`Exported ${cookies.length} cookies for ${url.hostname}`);

    } catch (error) {
      console.error('Error exporting site cookies:', error);
      alert('Failed to export site cookies: ' + (error as Error).message);
    }
  };

  const filteredCookies = cookies.filter(cookie =>
    cookie.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    cookie.domain.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-cyan-400"></div>
      </div>
    );
  }

  return (
    <div className="hud-card">
      {/* Header */}
      <div className="border-b border-cyan-300/20 px-4 sm:px-6 py-3 sm:py-4">
        <h2 className="hud-title">Cookie Tools</h2>
        <p className="text-sm text-gray-400">One-click export to clipboard (JSON/Netscape)</p>
      </div>

      <div className="p-4">
        <div className="hud-section mb-4">
          <div className="flex flex-wrap items-center gap-2 mb-3">
            <input
              type="text"
              placeholder="Search cookies..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="hud-input flex-1 min-w-0"
            />
            <button
              onClick={() => exportToClipboard('json')}
              className="hud-btn flex-shrink-0"
            >
              📋 Copy JSON
            </button>
            <button
              onClick={() => exportToClipboard('netscape')}
              className="hud-btn flex-shrink-0"
            >
              📋 Copy Netscape
            </button>
            <label htmlFor="import-cookies-file" className="hud-btn flex-shrink-0 cursor-pointer">
              📥 Import JSON
            </label>
            <input
              type="file"
              id="import-cookies-file"
              accept=".json"
              className="hidden"
              onChange={handleImportCookies}
            />
            <button
              onClick={exportSiteCookies}
              disabled={cookies.length === 0} // Disable if no cookies to export for the site
              className="hud-btn flex-shrink-0"
            >
              📤 Export Site Cookies
            </button>
          </div>
          
          <div className="text-xs text-gray-500 mb-3">
            Found {filteredCookies.length} cookie{filteredCookies.length !== 1 ? 's' : ''} for this site
          </div>
        </div>

        <div className="space-y-2 max-h-80 overflow-y-auto">
          {filteredCookies.length === 0 ? (
            <div className="text-center text-gray-500 py-8">
              No cookies found for this site
            </div>
          ) : (
            filteredCookies.map((cookie, index) => (
              <div key={index} className="hud-section flex items-center justify-between">
                <div className="flex-1">
                  <div className="font-medium text-sm text-cyan-400">{cookie.name}</div>
                  <div className="text-xs text-gray-400 mt-1">
                    Domain: {cookie.domain} | Path: {cookie.path}
                  </div>
                  <div className="text-xs text-gray-500 mt-1">
                    {cookie.secure && <span className="bg-cyan-600 text-white px-1 rounded text-xs mr-1">Secure</span>}
                    {cookie.httpOnly && <span className="bg-cyan-600 text-white px-1 rounded text-xs mr-1">HttpOnly</span>}
                    {cookie.expirationDate && <span className="text-gray-400">Expires: {new Date(cookie.expirationDate * 1000).toLocaleDateString()}</span>}
                  </div>
                  <div className="text-xs text-gray-400 mt-1 truncate">
                    Value: {cookie.value.length > 50 ? cookie.value.substring(0, 50) + '...' : cookie.value}
                  </div>
                </div>
                <button
                  onClick={() => deleteCookie(cookie)}
                  className="hud-btn hud-btn-danger ml-2"
                >
                  Delete
                </button>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );

};

export default CookieManager;
